"use client";

export const metadata = {"title":"Be BiteSmart — Parent-first digital strategy","description":"A parent-first digital strategy for Be BiteSmart, reorganising child-safety education around real parent needs, user journeys, content systems and governance."};
import Link from "next/link";
import {motion} from "framer-motion";

const phases=[
["01","Foundation","Establish the marketing foundation, clarify audiences and identify the systems needed for sustainable growth."],
["02","Parent-first strategy","Focus first on parents and caregivers, then test, measure, improve and validate before adapting the model for other audiences."],
["03","Digital experience","Shift the Parents experience from a collection of resources to a guided learning journey built around real parent situations."],
["04","Information architecture","Organise guidance around developmental stages and the questions parents naturally ask, rather than expecting them to navigate professional terminology."],
["05","Content strategy","Connect life stage, parent need and learning format so articles, Q&As, videos, downloads and evidence work as one content system."],
["06","Governance","Create standards for evidence, review, approval, translation, publishing and controlled updates for safety-sensitive content."]
];
const stages=["Planning for a Child","Pregnancy","Newborn","Crawling","Beginning to Walk","Toddler","Preschool","After a Bite"];
const lenses=[["LIFE STAGE","Where is the child developmentally?","Pregnancy · Baby · Toddler · Preschool"],["PARENT NEED","What is the parent trying to understand or do?","Prepare · Understand · Supervise · Recognise · Respond"],["LEARNING FORMAT","What is the most useful way to deliver the guidance?","Short answer · Guide · Video · Download · Evidence"]];
export default function BeBiteSmart(){return <main className="case">
<header className="nav"><Link className="brand" href="/">REGGIE.</Link><nav><Link href="/#work">WORK</Link><Link href="/#about">ABOUT</Link><Link href="/#contact">CONTACT</Link></nav></header>
<section className="case-hero"><Link className="back" href="/">← BACK TO SELECTED WORK</Link><p className="section-label">02 / STRATEGY · CASE STUDY</p><h1>Be BiteSmart</h1><p className="case-lead">Building a parent-first digital strategy for a child-safety education programme.</p><div className="case-meta"><span>ROLE<br/><b>Digital strategy</b></span><span>FOCUS<br/><b>Parents Learning Center</b></span><span>WORK<br/><b>Strategy · IA · Content · Governance</b></span></div></section>
<section className="case-problem"><p className="section-label">THE STRATEGIC QUESTION</p><div><h2>How do you turn strong educational resources into something parents can actually find, follow and use?</h2><p>Be BiteSmart already had a clear child-safety mission, evidence-informed guidance, videos and a comprehensive Parents Guide. The opportunity was not simply to create more material. It was to organise the existing and future resources around the situations parents actually experience.</p><p>The work therefore moved away from resource-first navigation and towards a parent-first learning system: begin with the audience, understand the experience, structure the information, connect the content and put controls around how safety guidance is maintained.</p></div></section>
<figure className="bbs-case-photo"><img src="https://images.pexels.com/photos/7677677/pexels-photo-7677677.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Parents and a young child walking a dog together outdoors"/><figcaption>CONTEXT IMAGE / PARENT · CHILD · DOG INTERACTION <span>PHOTO: PNW PRODUCTION / PEXELS</span></figcaption></figure>
<section className="progression"><p className="section-label">THE STRATEGY, BUILT IN STAGES</p><h2>From foundation<br/>to governance.</h2><div className="phase-list">{phases.map((p,i)=><motion.article key={p[0]} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.45}} transition={{delay:i*.04}}><span>{p[0]}</span><h3>{p[1]}</h3><p>{p[2]}</p></motion.article>)}</div></section>
<section className="case-shift"><p className="section-label">THE CORE SHIFT</p><div className="shift-grid"><div><small>RESOURCE-FIRST</small><p>Parents encounter guides, videos and existing site sections first.</p></div><div className="arrow">→</div><div><small>PARENT-FIRST</small><p>Parents begin with their situation, life stage, question or concern.</p></div></div></section>
<section className="parent-model"><p className="section-label">INFORMATION ARCHITECTURE</p><div className="model-head"><h2>Organised around the parent journey.</h2><p>Parents do not arrive thinking in website categories. They arrive with situations: a baby is coming home, a child has started crawling, a toddler keeps approaching the dog, or a bite has already happened. The architecture maps guidance to those moments.</p></div><div className="stage-track">{stages.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,"0")}</span><strong>{s}</strong></div>)}</div></section>
<section className="content-system"><p className="section-label">CONTENT STRATEGY</p><h2>One system.<br/>Three lenses.</h2><div className="lens-grid">{lenses.map((l,i)=><article key={l[0]}><span>0{i+1}</span><h3>{l[0]}</h3><p>{l[1]}</p><small>{l[2]}</small></article>)}</div><p className="principle">THE PARENT PROBLEM COMES FIRST. <i>THE FORMAT COMES SECOND.</i></p></section>
<section className="governance"><p className="section-label">GOVERNANCE</p><div><h2>Strategy does not stop at publication.</h2><p>For safety-sensitive guidance, consistency and traceability matter. The governance framework defined how content should move through evidence, editorial review, specialist validation, approval, translation and publication, with controlled updates after launch.</p><div className="govern-flow"><span>EVIDENCE</span><i>→</i><span>DRAFT</span><i>→</i><span>REVIEW</span><i>→</i><span>APPROVE</span><i>→</i><span>PUBLISH</span><i>→</i><span>MAINTAIN</span></div><p className="govern-note">The first-release governance baseline covers 60 canonical priority parent questions across Pregnancy, Baby, Toddler, Preschool, After a Bite and cross-stage guidance.</p></div></section>
<section className="case-close"><p className="section-label">WHAT THE WORK CREATED</p><h2>A strategy that connects audience, experience, structure, content and governance.</h2><p>Rather than treating digital strategy as a single campaign or website recommendation, the work established a framework that Be BiteSmart can continue to build, test and refine as the Parents Learning Center develops.</p><Link href="/">← RETURN TO SELECTED WORK</Link></section>
</main>}