"use client";
import {motion} from "framer-motion";
export default function PorterVoiceCollective(){return <main>
<header className="nav"><a className="brand" href="/">REGGIE.</a><nav><a href="/#work">WORK</a><a href="/#about">ABOUT</a><a href="/#contact">CONTACT</a></nav></header>
<section className="case-hero pvc-case"><a className="back" href="/">← BACK TO WORK</a><p className="section-label">03 / ANALYTICS</p><h1>Porter Voice<br/>Collective</h1><p className="case-lead">Turning cross-platform performance data into clearer signals about which stories connect, where, and why.</p><div className="case-meta"><span>ROLE<b>Marketing analytics</b></span><span>SYSTEM<b>Power BI reporting</b></span><span>CHANNELS<b>Instagram · Facebook · LinkedIn</b></span></div></section>
<section className="case-problem"><p className="section-label">THE CONTEXT</p><div><h2>Stories from the trails. Signals from the data.</h2><p>Porter Voice Collective shares the experiences of mountain tourism workers, including porters and guides from Nepal’s Himalayan trails, Peru’s Camino Inca and Tanzania’s Kilimanjaro.</p><p>My work brings performance data from its main social channels into a consolidated reporting system, making it easier to compare content performance, audience response and engagement patterns across platforms.</p></div></section>
<section className="pvc-findings"><p className="section-label">WHAT THE DATA REVEALED</p><h2>Different platforms were doing different jobs.</h2><div className="finding-grid"><motion.article initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><small>INSTAGRAM</small><strong>83.7%</strong><h3>A breakout post changed the scale of reach.</h3><p>One post accounted for most of the platform’s reach during the reporting period, showing why averages alone can hide what actually drove performance.</p></motion.article><motion.article initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:.1}}><small>LINKEDIN</small><strong>9.5×</strong><h3>Engagement told a stronger story than visibility.</h3><p>A breakout post ranked only fourth for impressions but first for engagement and engagement rate, pointing to unusually strong audience response rather than simply high exposure.</p></motion.article><motion.article initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:.2}}><small>FACEBOOK</small><strong>01</strong><h3>Content type mattered.</h3><p>Guest and panel-speaker content produced the strongest average reach in the content-type comparison, helping identify formats worth examining more closely.</p></motion.article></div></section>
<section className="case-shift"><p className="section-label">THE REPORTING SYSTEM</p><div className="shift-grid"><div><small>BEFORE</small><p>Separate platform metrics and isolated performance signals.</p></div><div className="arrow">→</div><div><small>AFTER</small><p>A consolidated Power BI view built for comparison and interpretation.</p></div></div></section>
<section className="pvc-process"><p className="section-label">FROM METRICS TO DECISIONS</p><h2>Platform data → Power BI → content signals → decisions.</h2><p>The purpose of the reporting is not simply to count reach or engagement. It is to identify patterns that can help Porter Voice Collective understand which stories and messages are resonating with audiences and how digital communications can better support its advocacy for workforce equity in tourism.</p></section>
<section className="case-close"><p className="section-label">THE QUESTION BEHIND THE DASHBOARD</p><h2>Which stories and messages are connecting with people?</h2><p>The answer changes by platform. The reporting system makes those differences visible without reducing performance to a single headline metric.</p><a href="/">← BACK TO SELECTED WORK</a></section>
</main>}