"use client";
import {motion} from "framer-motion";

const platforms=[["YOUTUBE","300"],["REDDIT","297"],["FACEBOOK","220"],["INSTAGRAM","103"],["X","100"]];
const frames=[["POLITICAL NEUTRALITY","69.7"],["ISRAEL / ANTISEMITISM","40.0"],["INSTITUTIONAL POWER","9.3"],["FREE EXPRESSION","8.7"],["COMMERCIAL / CONSUMER","7.7"],["ADVOCACY / SOLIDARITY","5.6"]];
export default function MacklemoreInvestigation(){return <main className="mk-case">
<header className="nav"><a className="brand" href="/">REGGIE.</a><nav><a href="/#work">WORK</a><a href="/#about">ABOUT</a><a href="/#contact">CONTACT</a></nav></header>

<section className="mk-hero"><div className="mk-hero-copy"><a className="back" href="/">← BACK TO WORK</a><p className="section-label">06 / INDEPENDENT INVESTIGATION</p><h1>Macklemore,<br/>Palestine and the<br/>Limits of Online<br/>Backlash</h1><p className="mk-deck">Beyond the noise, outrage and assumptions of a divided internet</p><div className="mk-meta"><span>METHOD<b>Manual content analysis</b></span><span>CORPUS<b>1,020 comments</b></span><span>SCOPE<b>5 platforms · 42 sources</b></span></div></div><figure className="mk-hero-photo"><img src="https://www.edgeofsports.com/column/macklemore-is-a-seattle-sports-superfan-now-he-is-also-a-target/img/column/primary.jpg" alt="Macklemore performing onstage during a concert"/><div className="mk-hero-overlay"><small>THE QUESTION</small><strong>Did the loudest reaction reflect what audiences actually wanted?</strong></div></figure></section>

<section className="mk-context"><div><p className="section-label">THE CONTROVERSY</p><h2>Backlash was visible.<br/>But visibility was not<br/>the same as consensus.</h2></div><div className="mk-context-copy"><p>After Macklemore made onstage statements in support of Palestine while opening for Ed Sheeran, criticism spread quickly online. He was subsequently removed from the remaining U.S. tour dates after venues objected to his participation.</p><p>The public conversation contained several questions at once: attitudes towards Macklemore, attitudes towards his advocacy, arguments about political expression, and whether removal from the tour was an appropriate consequence.</p><p>This investigation separated those signals rather than treating online reaction as a single measure of sentiment.</p></div></section>

<section className="mk-scope"><div className="mk-scope-head"><p className="section-label">THE EVIDENCE</p><h2>1,020 comments.<br/>42 source units.<br/>Five platforms.</h2><p>Comments were manually coded across YouTube, Reddit, Facebook, Instagram and X. The aim was not to estimate public opinion, but to examine the structure of the collected conversation.</p></div><div className="mk-platforms">{platforms.map((x,i)=><motion.div key={x[0]} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}}><b>{x[1]}</b><span>{x[0]}</span></motion.div>)}</div></section>

<section className="mk-finding mk-primary"><div className="mk-number"><strong>73.6%</strong><span>OPPOSED REMOVAL</span></div><div className="mk-finding-copy"><p className="section-label">01 / BACKLASH ≠ CONSEQUENCE</p><h2>The loudest criticism did not translate into majority support for removal.</h2><p>Among comments with an expressed removal position, opposition was substantially more common than support. Support for removal accounted for 14.9%, while 11.1% were neutral and 0.4% mixed.</p><div className="mk-position-bar"><i style={{width:"73.6%"}}></i><i style={{width:"14.9%"}}></i><i style={{width:"11.1%"}}></i><i style={{width:".4%"}}></i></div><div className="mk-bar-key"><span>73.6 OPPOSE</span><span>14.9 SUPPORT</span><span>11.1 NEUTRAL</span></div></div></section>

<section className="mk-split-signal"><div className="mk-signal"><small>CAUSE → ARTIST</small><strong>89.0%</strong><p>Among 73 comments supporting Palestine advocacy, 89.0% also supported Macklemore.</p></div><div className="mk-signal dark"><small>ARTIST → CONSEQUENCE</small><strong>0</strong><p>Among 46 Macklemore supporters with a removal position, none supported removal; 89.1% opposed it.</p></div></section>

<section className="mk-frames"><div className="mk-frames-copy"><p className="section-label">02 / INTERPRETATION MATTERED</p><h2>The same controversy produced very different demands depending on how people framed it.</h2><p>Removal support was highest when the issue was interpreted through political neutrality or politicisation. It was far lower in comments framed around free expression, institutional power, commercial action or advocacy.</p></div><div className="mk-frame-chart">{frames.map((f,i)=><div className="mk-frame-row" key={f[0]}><span>{f[0]}</span><div><motion.i initial={{width:0}} whileInView={{width:f[1]+"%"}} viewport={{once:true}} transition={{duration:.65,delay:i*.05}}></motion.i></div><b>{f[1]}%</b></div>)}</div></section>

<section className="mk-platform-section"><p className="section-label">03 / PLATFORM CONTEXT</p><h2>Where people talked changed how the conversation looked.</h2><div className="mk-platform-grid"><article><strong>24.9%</strong><span>REDDIT</span><p>Argument and explanation</p></article><article><strong>28.2%</strong><span>FACEBOOK</span><p>Ridicule and attack</p></article><article><strong>19.4%</strong><span>INSTAGRAM</span><p>Solidarity and advocacy</p></article></div><p className="mk-caution">Personal reaction remained the largest discourse category across all five platforms. These differences describe the sources in this dataset, not permanent characteristics of entire platform populations.</p></section>

<section className="mk-heat"><div className="mk-heat-copy"><p className="section-label">04 / HEAT ≠ CONSEQUENCE</p><h2>A conversation can be highly confrontational without producing strong demand for institutional action.</h2><p>Humour and ridicule showed approximately 95% discourse escalation but only 16.7% support for removal. Political neutrality and politicisation showed the reverse pattern: 69.7% removal support with comparatively low escalation.</p></div><div className="mk-quadrant"><span className="axis-y">MORE ESCALATION ↑</span><span className="axis-x">MORE REMOVAL SUPPORT →</span><i className="qline h"></i><i className="qline v"></i><div className="dot humor"><b>HUMOUR & RIDICULE</b><small>~95% escalation<br/>16.7% removal support</small></div><div className="dot politics"><b>POLITICAL NEUTRALITY</b><small>69.7% removal support</small></div><div className="dot advocacy"><b>ADVOCACY</b><small>low removal support</small></div></div></section>

<section className="mk-robust"><div><p className="section-label">05 / DOES THE SOURCE MIX MATTER?</p><h2>The number moved.<br/>The direction did not.</h2></div><div className="mk-weight"><div><strong>16.9%</strong><span>EVERY COMMENT<br/>WEIGHTED EQUALLY</span></div><b>→</b><div><strong>23.5%</strong><span>EVERY SOURCE<br/>GIVEN EQUAL INFLUENCE</span></div><p>Source composition affected the magnitude of removal support without reversing the overall direction: opposition remained more common under both approaches.</p></div></section>

<section className="mk-model"><div className="mk-model-head"><p className="section-label">06 / A MORE DEMANDING TEST</p><h2>Could the pattern still be distinguished when several signals were considered together?</h2><p>A logistic regression model tested clear support-versus-oppose removal comments. Theme and perceived harm produced an AUC of 0.83; adding platform context increased it to 0.87.</p></div><div className="mk-auc"><div><small>CONTENT ONLY</small><strong>0.83</strong><span>AUC</span></div><div><small>CONTENT + PLATFORM</small><strong>0.87</strong><span>AUC</span></div></div><p className="mk-model-note">These results describe discrimination within this dataset. They are not forecasts of public behaviour and do not establish causation.</p></section>

<section className="mk-close"><p className="section-label">WHAT THE INVESTIGATION SHOWED</p><h2>Online backlash is not one signal.</h2><div><p>Support for a cause, support for an artist, emotional intensity, discourse style and demand for consequences can move in different directions. Reading controversy well means separating them.</p><p>The analysis also showed why platform and source composition matter. The magnitude of a result can change depending on where evidence comes from, even when the broader direction remains visible.</p><a href="https://github.com/reggiemagtibay/macklemore-online-backlash-analysis" target="_blank" rel="noreferrer">VIEW PROJECT REPOSITORY ↗</a><a href="/">← BACK TO SELECTED WORK</a></div></section>
</main>}